In [8]:
import numpy as np

In [23]:
arr=np.array(32)

In [24]:
print(arr)

32


In [25]:
arr.ndim

0

In [28]:
arr.shape

()

In [29]:
arr=np.array([1])

In [30]:
print(arr)

[1]


In [31]:
arr.ndim

1

In [32]:
arr.shape

(1,)

In [33]:
arr=np.array([[1,2,3],[4,5,6]])

In [34]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [35]:
arr.ndim

2

In [36]:
arr.shape

(2, 3)

In [37]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [38]:
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [39]:
arr.ndim

3

In [40]:
arr.shape

(1, 3, 3)

In [41]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
arr=np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [44]:
arr=np.logspace(1,3,3)

In [45]:
print(arr)

[  10.  100. 1000.]


In [50]:
arr=np.logspace(1,3,3, base=2)
print(arr)

[2. 4. 8.]


In [52]:
arr=np.logspace(1,3,3, base=2)
print(arr)

[2. 4. 8.]
